<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Collections</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- NuGet Package Properties -->
        <PackageId>RrbList</PackageId>
        <Version>0.0.1</Version>
        <Authors>Linus Björnstam</Authors>
        <Company>Bjoli Express</Company>
        <Description>An implementation of a fast immutable list using RRB-Trees.</Description>
        <PackageTags>collections;immutable;rrb-tree;list</PackageTags>
        <RepositoryUrl>https://github.com/your-repo/RrbList</RepositoryUrl>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>

    </PropertyGroup>

</Project>
